my_dict = {
    'Accounting': [
        'Prof. Francis Iyoha',
        'Prof. UWUIGBE Uwalomwa',
        'Prof. OLUBUKUNOLA UWUIGBE',
        'Prof. Oliver Ike Inyiama',
        'Dr Dorcas Titilayo Adetula',
        'Dr. Ben-Caleb Egbide',
        'DR Kingsley ADEYEMO',
        'Dr. Ojeka Stephen',
        'Dr. Adeniran Samuel FAKILE',
        'Dr. Eriabie Sylvester',
        'Dr. Nwobu Amaka',
        'Dr. Omodero Onyinyechi',
        'Dr. Ezenwoke Omotola',
        'Dr. Olusanmi Olamide (ACA)',
        'Mr Osariemen Asiriuiwa',
        'Dr. Mrs Owolabi Folashade (ACCA, ACA)',
        'Mr. Ajetunmobi Opeyemi',
        'Mr. Ozordi Emmanuel',
        'Mr. Ilogho Simon',
        'Dr. Miss Okougbo Peace',
        'Dr. Mrs Oluseyi Sharon',
        'Mr. Alex Adegboye',
        'Mrs Ihuoma Emenike',
    ],
    'Architecture': [
        'Prof. A.P. Opoko',
        'Dr. A. A. Oluwatayo',
        'Dr. E. B. Aduwo ',
        'Dr. P. A. Aderonmu ',
        'Dr. I. C. Ezema',
        'Dr. O. Fulani ',
        'Dr. O. N. E. Ekhaese ',
        'Dr. B. A. Adewale ',
        'Dr. Oladunni O. Izobo-Martins ',
        'Dr. O. D. Babalola ',
        'Dr. O.J. Ediae ',
        'Dr. G.M. Alalade ',
        'Arc. A.B. Sholanke ',
        'Dr. O.F. Jegede ',
        'Arc. A.O. Owoseni ',
        'Mrs. O.C. Adetoro ',
        'Mr. O.O. Olagunju ',
        'Mr. A.A. Akinola ',
        'Mrs. V.A. Adeoye ',
        'Mrs O.F. Oni',
        'Prof Leke Oduwaye',
        'Dr. Cynthia Adeokun',
    ],
    'Banking and Finance': [
        'Dr. (Mrs.) Babajide, A. A.',
        'Dr Kehinde Adetiloye',
        'Prof. Ikpefan, O. A.',
        'Dr. Felicia Omowunmi Olokoyo',
        'Dr Omankhanlen,Alex Ehimare ',
        'Dr. Folasade Adegboye ',
        'Dr. Benjamin EHIKIOYA ',
        'Dr. Adesina Tolulope ',
        'Dr. Uzoma Achugamonu ',
        'Dr. Victoria Akinjare ',
        'Dr. Areghan Isibor ',
        'Mr. Osuma Godswill Osagie ',
        'Ms Olabisi Kafidiya',
    ],
    'Buiding Technology': [
        'Professor O. I. Fagbenle',
        'Dr. L. M.  Amusan',
        'Dr. J. D. Owolabi',
        'Dr. A. O. Ogunde',
        'Dr. O. Joshua',
        'Dr. I. O. Omuh',
        'Dr. (Mrs.) F. P. Tunji-Olayeni',
        'Mr. A. O. Afolabi',
        'Mr. R. A. Ojelabi ',
        'Mr. David O. Nduka ',
        'Mr Aigbe Fortune Eromosele',
        'Miss Akinbo Tomisin F.',
        'Mr. Benjamin Babalola ',
        'Mr Ajao Adekunle ',
        'Mr. B. F. Ogunbayo ',
        'Mr Kunle Elizah Ogundipe',
    ],
    'Biochemistry': [
        'PROFESSOR AFOLABI, Israel Sunmola',
        'PROFESSOR ADEBAYO, Abiodun Humphrey',
        'PROFESSOR CHINEDU, Shalom Nwodo',
        'PROFESSOR IWEALA, Emeka Eze Joshua',
        'PROFESSOR OGUNLANA, Olubanke Olujoke',
        'Dr. ROTIMI, Solomon Oladapo',
        'Dr. IMAGA, Ngozi O. Awa',
        'Dr. DOKUNMU, Titilope Modupe',
        'Dr. OMOTOSHO, Omolola Elizabeth',
        'Dr. ROTIMI, Oluwakemi Anuoluwapo',
        'Dr. YAKUBU, Omolara Faith',
        'Dr. OLAWOLE, Tolulope Dorcas',
        'Dr. JOEL, Wisdom Oluwayemi',
        'Dr. IHEAGWAM, Franklyn Nonso ',
        'Dr. DE CAMPOS, Opeyemi Christiana',
        'MR. ADELANI, Isaacson Bababode',
        'MRS OKENZE, Gloria Nwabugwu',
        'MISS. DANIA, Omoremime Elizabeth',
        'MISS. EBIGWAI, EvaristaAyodele',
    ],
    'Biological Sciences': [
        'Professor ORANUSI Solomon (HOD) ',
        'Prof. OBEMBE Olawole Odun ',
        'Professor OMONHINMIN Asotie Conrad ',
        'Prof. NWINYI, Obinna Chukwuemeka',
        'Dr. ENI, Angela Obiageli ',
        'Dr. OLASEHINDE, Grace Iyabo ',
        'Dr. AKINNOLA Olayemi Oluseun',
        'Dr. AYANDA Isaac Opeyemi ',
        'Dr. POPOOLA Jacob Olagbenro ',
        'Dr. Tersagh Ichor',
        'Dr. EJOH Akpoyovware Samuel ',
        'Dr. AHUEKWE Eze Frank ',
        'Dr. ISIBOR Patrick Omoregie ',
        'Dr. AKINDUTI Paul ',
        'Dr. OZIEGBE Olubukola ',
        'Dr. Bunmi Olopade',
        'Mrs. ATOLAGBE Oluwabunmi ',
        'Dr. BELLO Oluwakemi Adetutu ',
        'Mrs. Benson Adeola ',
        'Mrs. OSHAMIKA Oyewumi ',
        'Dr. ONIHA Margaret Ikhiwili ',
        'Mr. AWORUNSE Rotimi Samuel ',
        'Mrs. Ajiboye Babafemi Ibukun',
        'Mr. OYESOLA Olusola Luke ',
        'Mr. OYEWALE John ',
        'Miss OBAFEMI Yemisi Dorcas ',
    ],
    'Business Management': [
        'Prof.  Adeniji, Anthonia  Adenike',
        'Prof. Chinonye Love Moses',
        'Prof. Rowland Kpasome Enwuzuruike',
        'Dr. Kehinde, Oladele Joseph',
        'Dr. Adegbuyi, Omotayo Adeniyi ',
        'Dr. Osibanjo, Adewale Omotayo',
        'Dr. Ogunnaike, Olaleke Oluseye',
        'Dr. Igbinoba, Edith Ebeguki',
        'Dr. Ogbari, Ejovwokeoghene Mercy',
        'Dr. Agboola, Mayowa Gbenga',
        'Dr. Akinbode, Mosunmola Oluwafunmilayo',
        'Dr. Amaihian, Augusta Bosede',
        'Dr. Falola Hezekiah Olubusayo',
        'Dr. Ibidunni Ayodotun Stephen',
        'Dr. Oyewunmi, Adebukola Esther',
        'Dr. Salau, Odunayo Paul',
        'Dr. Adeniji, Chinyerem Grace',
        'Dr. Ufua Daniel',
        'Dr. Adegbuyi Abimbola',
        'Dr. Atolagbe Tolulope',
        'Mrs. Aka  Deborah Oluwaseun',
        'Dr.Opeyemi Ogueyungbo',
        'Efe-Imafidon Emmanuel',
        'Gberevbie Marvellous',
        'Miss Busola Kehinde',
        'Ogueyungbo Opeyemi Olunike',
        'Gberevbie Marvellous Aghogho Chidinma',
        'Kehinde Busola Elizabeth',
        'Efe-Imafidon Emmanuel Odion',
    ],
    'Chemical Engineering': [
        'Prof. J.A. Omoleye',
        'Prof. V. E. Efeovbokhan',
        'Dr. A. O. Ayeni ',
        'Dr A. A. Ayoola ',
        'Dr (Mrs) Agboola',
        'Dr (Mrs) M. Ojewumi',
        'Dr. S. Sanni',
        'Dr (Mrs.) E. Alagbe',
        'Engr. O. A. Adeeyo',
        'Dr Elehinafe F. ',
        'Dr. (Miss) Babatunde D.E',
        'Dr (Mrs.) Oladimeji T. E.',
        'Mr A. T. Ogunbiyi',
        'Dr (Mrs.) Obanla O. R.',
        'Engr. (Mrs) O. Abatan',
        'Dr. Olagoke Oladokun',
        'Mrs Fagbiele. O.',
        'Dr O. A. Odunlami',
    ],
    'Chemistry': [
        'Prof. Joseph A. O. Olugbuyiro',
        'Prof. Kolawole O. Ajanaku ',
        'Prof. Olayinka O. Ajani',
        'Prof. Akan B Williams.',
        'Prof. Nsikak U. Benson ',
        'Prof. Atasie, V. N',
        'Dr. Tolutope O. Siyanbola ',
        'Dr. C. O. Ehi-Eromosele',
        'Dr. Joseph A. Adekoya ',
        'Dr. M.M. Solomon ',
        'Dr. W. U. Anake',
        'Dr. A. A. Akinsiku ',
        'Dr. A. A. Adebisi ',
        'Dr. E. A. Adedapo ',
        'Dr. A. T. Etchie',
        'Dr. A. Edobor-Osoh',
        'Dr. C. O. Ajanaku ',
        'Dr. O. Aladesuyi ',
        'Dr. I. O. Olanrewaju ',
        'Dr. O. H. Fred-Ahmadu ',
        'Mrs. O. T. Ademosun',
        'Mr. S.O. Ajayi ',
    ],
    'Computer and Information Sciences': [
        'Dr. (Mrs) O. O. Oladipupo (HOD)',
        'Prof. A. A. Azeta',
        'Prof. E. F. Adebiyi',
        'Prof. V. C. Osamor',
        'Prof. A. A. Adebiyi ',
        'Dr. Olanrewaju Jelili Oyelade',
        'Dr. I. Odun-Ayo ',
        'Dr. I. T. Afolabi ',
        'Dr. M. Adebiyi ',
        'Dr. A. A. Oni ',
        'Dr. S. R. Okuboyejo ',
        'Dr. A. A. Ezenwoke ',
        'Dr. O. C. Emebo ',
        'Dr. I. M. Isewon ',
        'Dr. Adesola Falade ',
        'Dr. Oluranti Jonathan ',
        'Mr. B. O. Odusote ',
        'Mrs T. O. Oladimeji ',
        'Mrs Victoria Samuel ',
        'Dr. O. U. Iheanetu ',
        'Mr Stephen Adubi ',
        'Mrs Theresa Abiodun ',
    ],
    'Civil Engineering': [
        'Anthony Nkem Ede, PhD',
        'David O. Omole, PhD',
        'David O. Olukanni, PhD',
        'Mrs Olatokumbo Ofuyatan, PhD',
        'Gideon O. Bamigboye, PhD',
        'Isaac I. Akinwumi, PhD',
        'Paul O. Awoyera, PhD',
        'Oluwarotimi M. Olofinnade, PhD',
        'Engr C. P. Emenike',
        'Dr. Chukwueloka Okeke',
        'Solomon O. Oyebisi',
        'Mrs O. G. Mark',
        'Surv. A. S. Ojo',
        'Engr. Sanni Reuben',
        'Engr. Akpabot Akpabot',
        'Gideon A. Adeyemi',
        'Engr. Muyiwa Onakunle',
        'Engr. Abimbola Odetoyan',
        'Engr. John Oluwafemi',
        'Mrs K. Daramola',
        'B. I. Oniemayi',
        'Mr. Justin Lazarus',
    ],
    'Economics and Development Studies': [
        'Evans Osabuohien ',
        'Isaiah Olurinola ',
        'Philip Alege',
        'Dr. Azuh Dominic ',
        'Dr. Ebenezer Bowale ',
        'Dr. Henry Okodua',
        'Dr. Emmanuel Amoo ',
        'Dr. Gershon Obindah ',
        'Dr. Oluwatoyin Matthew ',
        'Dr. Muyiwa Oladosun ',
        'Dr. Fasina Fagbeminiyi ',
        'Dr. Moses Akanbi ',
        'Dr. Olabanji Ewetan ',
        'Dr. Adeyemi Ogundipe ',
        'Dr Oluwatomisin Ogundipe',
        'Dr. Oluyomi Ola-David ',
        'Dr. Urhie Ese',
        'Dr. Oluwasogo Adediran ',
        'Dr. Aderounmu ',
        'Dr. Oluwarotimi Owolabi ',
        'Dr. Ngozi Adeleye ',
        'Dr. Ifeoluwa Israel Ogunrinola',
        'Dr. Adebanke Olawole-Isaac',
        'Dr. Opeyemi Esther Babajide',
        'Dr. Paul O. Adekola',
        'Dr. Uchechukwu Emena Okorie',
        'Dr. Jeremiah Ogaga Ejemeyovwi',
        'Dr. Queen Esther Oye',
        'Romanus Osabohien ',
        'Abidemi Alejo',
        'Victoria Isioma Okafor',
    ],
    'Electrical and Electronics Engineering': [
        'Prof. Anthony U. Adoghe',
        'Prof. AAA Atayero',
        'Prof. Sanjay Misra',
        'Prof. F. E. Idachaba',
        'Prof. Emmanuel Adetiba (HOD)',
        'Dr. Ayoade Felix Agbetuyi ',
        'Engr (Dr.) Hope Orovwode ',
        'Dr. Ademola Abdulkareem ',
        'Dr. Ayokunle A. Awelewa ',
        'Dr. Badejo Joke Atinuke',
        'Dr. Adeyinka Ajao Adewale',
        'Dr. Samuel Isaac Adekunle ',
        'Dr. Oguntosin Victoria',
        'Dr. Olowoleni Joseph Oluwole ',
        'Engr. Adelakun Adebiyi Adisa',
        'Engr. Olaitan Alasiri',
        'Mrs Timilehin Fiyinfoluwa Sanni ',
        'Engr. Shomefun Tobi E. ',
        'Engr. Amuta Elizabeth. O. ',
        'Mr. Olajube Ayobami Aremu ',
        'Dr. Okokpujie Kennedy',
        'Dr. Oshin Oluwadamilola Adu',
        'Dr. Adesina Tolulope',
        'Mrs. Odu Tiwalade O.',
        'Mrs. Takpor Temitope Oluwatosin',
        'Mrs. Steve-Essi Onyinyechi F. ',
        'Mr. Omoruyi Osemwegie',
        'Mr. Michael O. Adedokun',
        'Mr. Okoyeigbo Obinna',
        'Mrs. Mercy Kayode-Adeyemi',
        'Mr. Etinosa Noma-Osaghae',
        'Engr. Orimogunje Abidemi M',
        'Engr. IFIJEH AYODELE HEPHZIBAH',
        'Mr. ABUBAKAR JOHN',
        'Miss. OWUAMA C. EBERE',
        'Miss LAWAL COMFORT',
    ],  
    'Estate Management': [
        'Prof. M.O. Ajibola',
        'Dr. Caleb Abiodun Ayedun ',
        'Dr. Iroham Osmond Chukwuemeka ',
        'Dr. (Mrs) A.O. Oluwunmi ',
        'Dr. Olayinka C. Oloke ',
        'Dr. Omolade Adedoyin Akinjare ',
        'Dr. (Mrs.) A.O. Oluwatobi ',
        'Dr. A.S. Oni ',
        'Dr. Nkolika Peter ',
    ],
    'Languages and General Studies': [
    ],
    'Mass Communication': [
        'Dr Oladokun Omojola ',
        'Dr Lanre Amodu ',
        'Dr Stella Aririguzoh ',
        'Dr. Oscar Odiboh ',
        'Dr Kehinde Oyesomi (HOD)',
        'Dr Ada Peter ',
        'Dr Olatunji Oyedepo ',
        'Miss Igbinoba Angie',
        'Dr Funke Omole ',
        'Dr Tolu Kayode-Adedeji ',
        'Dr Thelma Ekanem ',
        'Dr Adeyeye Babatunde ',
        'Dr Adesina Evaristus ',
        'Dr Yartey Darlynton Albert ',
        'Mrs Folafunmi Bamigbolayin-Afolabi',
        'Mrs Aramide Aluko',
    ],
    'Mathematics': [
        'Prof. Samuel A. Iyase ',
        'Dr. Timothy A. Anake ',
        'Dr. Michael C. Agarana ',
        'Dr. Jimevwo G. Oghonyon ',
        'Dr. Olasunmbo O. Agboola ',
        'Dr. Hilary I. Okagbue ',
        'Mr. Ogbu F. Imaga ',
        'Dr. Abiodun A. Opanuga ',
        'Dr. Oluwole A. Odetunmibi ',
        'Mr. Opeyemi P. Ogundile ',
        'Dr. Sunday O. Edeki ',
        'Dr. Adedayo F. Adedotun',
        'Mr. Gabriel O. Odekina',
        'Dr. Grace O. Alao ',
        'Mr Peter O. Ogunniyi ',
    ],
    'Mechanical Engineering': [
        'Prof. J. O. Okeniyi ',
        'Prof. S. O. Oyedepo ',
        'Prof. A. O. Inegbenebor',
        'Prof. Oluseyi O. Ajayi ',
        'Prof. O. Ohunakin ',
        'Prof. Roland Tolulope Loto ',
        'Dr. P. O. Babalola ',
        'Dr. O. A. Omotosho ',
        'Dr. (Engr.) KILANKO Oluwaseun ',
        'Dr. Mfon Udo',
        'Dr. S. A. Afolalu ',
        'Dr. O. Joseph ',
        'Dr. O. Leramo ',
        'Dr. A. Aworinde',
        'Engr. Joseph Azeta ',
        'Dr. F. Muyiwa ',
        'Dr. J. Dirisu ',
        'Dr. Enesi Yekini Salawu ',
        'Dr. I. P. Okokpujie ',
        'Dr. Udoye Nduka ',
        'Dr. Alaba Oladeji Araoyinbo',
    ],
    'Petroleum Engineering': [
        'Professor Oyinkepreye David Orodu',
        'Dr. O.J Rotimi',
        'Dr. Gbadegesin Abiodun Adeyemi',
        'Dr Anthony Ameloko',
        'Dr Fred Temitope Ogunkunle',
        'Dr. D.O Oladepo',
        'Dr. K.B Orodu',
        'Dr. Charles Onuh',
        'Dr oluwasanmi olabode ',
        'Dr. O.O Mosobalaje',
        'Dr. (Mrs.) D.V. Abraham',
        'Miss Rachael Josephs',
    ],
    'Physics': [
        'Prof. Mojisola Usikalu (HOD)',
        'Marvel Akinyemi ',
        'Professor Temidayo Victor Omotosho',
        'Prof. Ahzegbobor Philip Aizebeokhai ',
        'Dr. Omeje Maxwell ',
        'Dr Moses Emetere ',
        'Dr Theophilus Aanuoluwa ADAGUNODO ',
        'Dr. Olusegun Adewoyin ',
        'Dr. Kehinde David Oyeyemi ',
        'Dr  Sule R',
        'Dr. Justina Achuka ',
        'Dr. OLAWOLE OLUKUNLE CHARLES ',
        'Dr. SAYO AKINWUMI ',
        'Dr. Temitope Abodunrin',
        'Mr. Iyanuoluwa Ogunrinola ',
        'Dr. Olusola Kayode ',
        'Mr.T.E Arijaje ',
        'Mr. Akinwumi Akinpelu ',
        'Mr. Idowu Babarimisa ',
        'Mr. WILLIAMS A. AYARA ',
        'Mr ifeanyi Araka ',
        'MR AYANBISI O ayanbisi oluwasegun ',
    ],
    'Political Science and International Relations': [
        'Professor GBEREVBIE, Daniel Eseme Idowu',
        'Professor FOLARIN, Sheriff F',
        'Dr. DURUJI, Moses',
        'Dr. ONI, Samuel',
        'Dr. CHIDOZIE, Felix',
        'Dr. OWOLABI, Fadeke',
        'Dr ONOR, Kester',
        'Dr. OLANREWAJU, Ilemobola',
        'Dr. AJAYI, Lady Adaina',
        'Dr. OLANREWAJU, Faith Osasumwen ',
        'Dr. AJAYI, Olumuyiwa',
        'Mrs. EXCELLENCE-OLUYE, Nchekwube',
        'Dr. ABASILIM, Ugochukwu David',
        'Dr. NJOAGUANI, Oluwatobi',
        'Dr. OYEYEMI, Adeola I.',
        'Dr. UDOH, Oluwakemi',
        'Mr OLANREWAJU, Adekunle',
        'Mr. AYODELE, Olaniyi',
        'Mr. FOLORUNSO, Gideon Ibukuntomiwa',
        'Mr DEINDE-ADEDEJI, Oluwatimilehin',
    ],
    'Psychology': [
        'Dr. S. O. Adeusi ',
        'Prof. A. M. Gesinde ',
        'Prof. O. A. Adekeye ',
        'Dr. G. O. Adejumo ',
        'Dr. I. K. Evbuoma ',
        'Dr. B. C. E. Agoha ',
        'Dr. A. O. Elegbeleye ',
        'Dr. E. I. Olowookere',
        'Mr. O. A. Akinfolarin ',
        'Mrs. C. O. Akinfolarin',
        'Mrs. A.T Akinboye ',
        'Prof. O.B.Ehigie. Benjamin',
        'Mrs. Taiwo A. Akinboye',
    ],
    'Sociology': [
        'Dr. T. O. George ',
        'Dr. D. Imhonopi ',
        'Dr. M. E. Egharevba ',
        'Dr. A. E. Jegede',
        'Dr. Ajayi Mofoluwake Paula',
        'Dr. Olawande Tomike',
        'Dr. Christianah Adetunde',
        'Dr. M. I. Ozoya',
        'Dr. Allo Tolulope',
        'Dr. Mercy Adebayo',
        'Mr Olawale Olonode',
        'Mr. Amos Olore',
    ]
}

user_input = 'ade'

for key, values in my_dict.items():
    for value in values:
        if user_input in value.lower():
            print(value)
            print(key)
            print()
